// ignore_for_file: constant_identifier_names

const String OBScreenOneRoute = '/';
const String OBScreenTwoRoute = 'obScreenTwo';
const String OBScreenThreeRoute = 'obScreenThree';
const String SignInRoute = 'signIn';
const String SignUpRoute = 'signUp';
const String SignupProcessRoute = 'signupProcess';
const String PaymentMethodRoute = 'paymentMethod';
const String backScreenRoute = 'backScreen';
const String uploadImageRoute = 'uploadImage';
const String ImagePreviewRoute = 'imagePreview';
const String SetLocationRoute = 'setLocation';
const String SignupSuccessRoute = 'signupSuccess';
const String VIaMethodRoute = 'viaMethod';
const String ResetPasswordRoute = 'resetPassword';
const String SuccessNotificationRoute = 'successNotification';
const String MainHomePageRoute = 'mainHome';
const String ExploreRestturantPageRoute = 'exploreResturant';
const String FilterRoute = 'filter';
const String ExploreMenuRoute = 'exploreMenu';
const String ExploreRestturantWithFilterPageRoute =
    'exploreResturantWithFilter';
const String ExploreMenuWithFilterRoute = 'exploreMenuWithFilter';
const String MessageRoute = 'message';
const String MessageDetailsRoute = 'messageDetails';
const String CallRingingRoute = 'callRinging';
const String CallingRoute = 'calling';
const String FinishOrderRoute = 'finishOrder';
const String RateFoodRoute = 'rateFood';
const String RateResturatRoute = 'rateResturat';
const String VoucharPromoRoute = 'voucharPromo';
const String notificationRoute = 'notification';
const String OrderDetailsRoute = 'orderDetailsRoute';
const String PaymentsRoute = 'payments';
const String EditLocationRoute = 'editLocation';
const String YourOrdersRoute = 'yourOrders';
const String ProductDetailsRoute = 'productDetails';
const String DetailsMenuRoute = 'detailsMenu';
